### ISSUE TITLE
Upgrade notes for 3.2.x do not mention new ruby version requirements 

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#15437]
### Expected behaviour

Either Mastodon 3.2.x fixes support for Ruby 2.5 (#15306), or explicitly says it doesn't support it anymore in its release notes.

### Actual behaviour

After upgrading from 3.1.5 to 3.2.2, I'm getting this in the logs:

```
2020-12-27T09:35:58.246Z pid=19013 tid=ovo86kb1p WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"BlockWorker","args":[<redacted>,<redacted>],"jid":"52d96a278c564ee596d843c5","created_at":1609060470.73756,"enqueued_at":1609061757.8207633,"error_message":"undefined method `filter' for #<Array:0x00007fe4b15340d8>","error_class":"NoMethodError","failed_at":1609060470.8119555,"retry_count":5,"retried_at":1609061085.039118},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"BlockWorker\",\"args\":[<redacted>,<redacted>],\"jid\":\"52d96a278c564ee596d843c5\",\"created_at\":1609060470.73756,\"enqueued_at\":1609061757.8207633,\"error_message\":\"undefined method `filter' for #<Array:0x00007fe4b15340d8>\",\"error_class\":\"NoMethodError\",\"failed_at\":1609060470.8119555,\"retry_count\":5,\"retried_at\":1609061085.039118}"}
2020-12-27T09:35:58.255Z pid=19013 tid=ovo86kb1p WARN: NoMethodError: undefined method `filter' for #<Array:0x00007fac1e31b240>
2020-12-27T09:35:58.255Z pid=19013 tid=ovo86kb1p WARN: /home/mastodon-code/mastodon/app/lib/feed_manager.rb:133:in `clear_from_timeline'
/home/mastodon-code/mastodon/app/services/after_block_service.rb:16:in `clear_home_feed!'
/home/mastodon-code/mastodon/app/services/after_block_service.rb:8:in `call'
```

### Steps to reproduce the problem

Run Mastodon with Ruby 2.5.

### Specifications

Mastodon 3.2.2

**Comment by ThibG** [comment]
oof, this is a bug that's been left in 3.2.x, but I believe it's actually fixed in 3.3.0

**Comment by ProgVal** [comment]
Any chance there will be a fix for this in 3.2.x?

**Comment by ClearlyClaire** [comment]
Seems like I missed this when backporting fixes to 3.2.1 :weary:
I guess we could push a 3.2.3… not sure it's worth it :/
I'll edit the release notes in the meantime
