### ISSUE TITLE
Sidekiq error in ActivityPub::ProcessingWorker

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#34886]
### Steps to reproduce the problem

in the sidekiq dead queue

```
Error Class     NoMethodError
Error Message     undefined method 'by_name' for class FeaturedTag
Error Backtrace     /usr/local/bundle/gems/activerecord-8.0.2/lib/active_record/dynamic_matchers.rb:22:in 'ActiveRecord::DynamicMatchers#method_missing'
/opt/mastodon/app/lib/activitypub/activity/remove.rb:34:in 'ActivityPub::Activity::Remove#remove_featured_tags'
/opt/mastodon/app/lib/activitypub/activity/remove.rb:11:in 'ActivityPub::Activity::Remove#perform'
```

### Expected behaviour

no error

### Actual behaviour

error

### Mastodon instance

aus.social

### Mastodon version

main. 7f4ec7d

**Comment by ClearlyClaire** [comment]
Seems like a regression from #34489, which removed the `by_name` scope.
