### PR TITLE
Fix Delete activity handling when the status has been reblogged (regression from #4706)

### PR DESCRIPTION
**Pull request by unarist**
```
sidekiq_1    | 2017-08-28T17:55:22.687Z 1 TID-41xbqwa8 WARN: NoMethodError: undefined method `id' for 1:Integer
sidekiq_1    | Did you mean?  i
sidekiq_1    | 2017-08-28T17:55:22.687Z 1 TID-41xbqwa8 WARN: /mastodon/app/lib/activitypub/activity/delete.rb:20:in `block in forward_for_reblogs'
sidekiq_1    | /usr/local/bundle/gems/sidekiq-bulk-0.1.1/lib/sidekiq/bulk.rb:13:in `map'
sidekiq_1    | /usr/local/bundle/gems/sidekiq-bulk-0.1.1/lib/sidekiq/bulk.rb:13:in `push_bulk!'
sidekiq_1    | /usr/local/bundle/gems/sidekiq-bulk-0.1.1/lib/sidekiq/bulk.rb:7:in `block in push_bulk'
sidekiq_1    | /usr/local/bundle/gems/sidekiq-bulk-0.1.1/lib/sidekiq/bulk.rb:6:in `each'
sidekiq_1    | /usr/local/bundle/gems/sidekiq-bulk-0.1.1/lib/sidekiq/bulk.rb:6:in `push_bulk'
sidekiq_1    | /mastodon/app/lib/activitypub/activity/delete.rb:19:in `forward_for_reblogs'
sidekiq_1    | /mastodon/app/lib/activitypub/activity/delete.rb:11:in `perform'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:42:in `process_item'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:33:in `block in process_items'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:33:in `reverse_each'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:33:in `each'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:33:in `map'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:33:in `process_items'
sidekiq_1    | /mastodon/app/services/activitypub/process_collection_service.rb:20:in `call'
sidekiq_1    | /mastodon/app/workers/activitypub/processing_worker.rb:9:in `perform'
```

### CODE REVIEW

File: app/lib/activitypub/activity/delete.rb [hunk 1]
```diff
@@ -16,7 +16,7 @@ def perform
   private
 
   def forward_for_reblogs(status)
-    ActivityPub::RawDistributionWorker.push_bulk(status.reblogs.includes(:account).references(:account).merge(Account.local).pluck(:account_id)) do |account|
+    ActivityPub::RawDistributionWorker.push_bulk(status.reblogs.includes(:account).references(:account).merge(Account.local)) do |account|
       [payload, account.id]
```
Comment (Gargron) [inline app/lib/activitypub/activity/delete.rb]: Whoops, I should have done `do |account_id|` and used that

**Review by Gargron — APPROVED** [review]
