### ISSUE TITLE
Sidekiq logs revealing logs of RemovalWorker NoMethodErrors

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#33319]
### Steps to reproduce the problem

```
tid=17uuvf WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[103923363673461248,{"redraft":false}],"class":"RemovalWorker","jid":"ebc025d875f8dc1417257abd","created_at":1734268481.9836564,"enqueued_at":1734329837.034052,"error_message":"undefined method `path' for nil","error_class":"NoMethodError","failed_at":1734268487.7721097,"retry_count":12,"retried_at":1734309083.5495784}}
tid=17uuvf WARN: NoMethodError: undefined method `path' for nil
tid=17uuvf WARN: /opt/mastodon/app/models/media_attachment.rb:330:in `animated_image?'
```

```
tid=19hb0b WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111198252114267521,{"redraft":false}],"class":"RemovalWorker","jid":"37dfdd0a855021e91677610c","created_at":1734270885.8850095,"enqueued_at":1734332107.8845046,"error_message":"undefined method `>' for nil","error_class":"NoMethodError","failed_at":1734270893.8729603,"retry_count":12,"retried_at":1734311356.1291895}}
tid=19hb0b WARN: NoMethodError: undefined method `>' for nil
tid=19hb0b WARN: /opt/mastodon/app/models/featured_tag.rb:50:in `decrement'
```

### Expected behaviour

No errors

### Actual behaviour

Errors

### Mastodon instance

aus.social

### Mastodon version

v4.4.0-alpha.1 / Main latest (minus 11 commits)

### Technical details

Mastodon 4.4.0-alpha.1
Ruby 3.3.6p108
PostgreSQL 16.6
Redis 7.4.1
Elasticsearch 8.14.1
libvips 8.16.0
FFmpeg 7.1

**Comment by shleeable** [comment]
first might be a regression from #28516 

second might be a regression from #32787
