### ISSUE TITLE
Building mastodon fails at google-protobuf dependency

### ISSUE THREAD

**Issue by Vamp898** [mastodon/mastodon#34606]
### Steps to reproduce the problem

1. Following the build steps at https://docs.joinmastodon.org/admin/install/
2. See how it fails during building google-protobuf

### Expected behaviour

Building should work fine

### Actual behaviour

Building doesn't work

### Detailed description

As usual after larger system Upgrade of the Host OS, i have to rebuild mastodon or at least re-run bundle install

Normally this works but this time, it fails during building google-protobuf with the following errors

---8<---
convert.c:312:5: error: format not a string literal and no format arguments [-Werror=format-security]
  312 |     rb_raise(rb_eRuntimeError, upb_Status_ErrorMessage(&status));
[...]
message.c:681:5: error: format not a string literal and no format arguments [-Werror=format-security]
  681 |     rb_raise(cParseError, upb_Status_ErrorMessage(&status));
---8<---

I even tried a fresh/clean/new git clone of the whole repo to built from scratch, but i end up with the exact same error at the same position.

Is there any workaround or something like that? As of now, it seems to be impossible to built Mastodon as one of its dependencies refused to build.

I checked if it is related to the GCC-15 Update but i get the same error with GCC-14

### Mastodon instance

mastodon.ikaros.space

### Mastodon version

v4.3.7

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.4.3
- Node.js version: 23.9.0

**Comment by Vamp898** [comment]
I found an (closed) Upstream Bug describing this exact issue, i asked there too
https://github.com/protocolbuffers/protobuf/issues/19938

**Comment by Vamp898** [comment]
Found an Workaround
bundle config --local build.google-protobuf "-- --with-cflags='$(ruby -r rbconfig -e 'print RbConfig::CONFIG["CFLAGS"]' | sed -e 's/-Werror=format-security//' -e 's/-flto=auto/-fno-lto/')' --with-ldflags='$(ruby -r rbconfig -e 'print RbConfig::CONFIG["LDFLAGS"]' | sed -e 's/-flto=auto/-fno-lto/')'"

**Comment by WRMSRwasTaken** [comment]
Well this shouldn't be closed IMHO because I just ran into this issue while building.

**Comment by Vamp898** [comment]
@WRMSRwasTaken After the bump to 3.25.7 i just ran into the next issue that it can't be built with LTO. So a pure dependency bump should not fix the issue. Its two issues.

One issue that is fixed by the bump to 3.25.7 is the Werror=format-security, but the LTO one still persists and that is nothing that can be fixed without changing the bundle command as shown above.
