### ISSUE TITLE
assets:precompile fails after upgrading to 4.3.0

### ISSUE THREAD

**Issue by Foritus** [mastodon/mastodon#32329]
### Steps to reproduce the problem

Upgrading from 4.2.13 using the instructions here https://github.com/mastodon/mastodon/releases/tag/v4.3.0.
Non-docker.

### Expected behaviour

The UI renders

### Actual behaviour

White screen, errors in server log

### Detailed description

```
mastodon@mastodon:~/live$ RAILS_ENV=production bundle exec rails assets:precompile                                                                                                                                                                                                       
I, [2024-10-08T22:21:28.768519 #7754]  INFO -- : [dotenv] Loaded .env.production                                                                                                                                                                                                         
Compiling...                                                                                                                                                                                                                                                                             
Compilation failed:                                                                                                                                                                                                                                                                      
(node:7812) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.                                                                                                                                                                      
(Use `node --trace-deprecation ...` to show where the warning was created)                        
```

this then results in the web UI being broken, with the service logging this error:
```
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] ActionView::Template::Error (Webpacker can't find mastodon-light.css in /home/mastodon/live/public/packs/manifest.json. Possible causes:                                                                   
Oct 08 22:27:51 mastodon bundle[1008]: 1. You want to set webpacker.yml value of compile to true for your environment                                                                                                                                                                    
Oct 08 22:27:51 mastodon bundle[1008]:    unless you are using the `webpack -w` or the webpack-dev-server.                                                                                                                                                                               
Oct 08 22:27:51 mastodon bundle[1008]: 2. webpack has not yet re-run to reflect updates.                                                                                                                                                                                                 
Oct 08 22:27:51 mastodon bundle[1008]: 3. You have misconfigured Webpacker's config/webpacker.yml file.                                                                                                                                                                                  
Oct 08 22:27:51 mastodon bundle[1008]: 4. Your webpack configuration is not creating a manifest.                                                                                                                                                                                         
Oct 08 22:27:51 mastodon bundle[1008]: Your manifest contains:                                                                                                                                                                                                                           
Oct 08 22:27:51 mastodon bundle[1008]: {                                                                                                                                                                                                                                                 
Oct 08 22:27:51 mastodon bundle[1008]: }                                                                                                                                                                                                                                                 
Oct 08 22:27:51 mastodon bundle[1008]: ):                                                                                                                                                                                                                                                
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]      5:     %meta{ charset: 'utf-8' }/                                                                                                                                                                     
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]      6:     %title= safe_join([yield(:page_title), Setting.default_settings['site_title']], ' - ')
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]      7:     %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]      8:     = theme_style_tags Setting.default_settings['theme']
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]      9:     = javascript_pack_tag 'common', crossorigin: 'anonymous'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]     10:     = javascript_pack_tag 'error', crossorigin: 'anonymous'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]     11:   %body.error
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd]
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] lib/webpacker/helper_extensions.rb:10:in `stylesheet_pack_tag' 
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/helpers/theme_helper.rb:7:in `block in theme_style_tags'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/helpers/theme_helper.rb:6:in `theme_style_tags'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/views/layouts/error.html.haml:8
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/controllers/application_controller.rb:167:in `block (2 levels) in respond_with_error'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/controllers/application_controller.rb:166:in `respond_with_error'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] app/controllers/application_controller.rb:100:in `not_found'
Oct 08 22:27:51 mastodon bundle[1008]: [67986572-7d1d-4963-8490-6d6319790ecd] lib/mastodon/rack_middleware.rb:9:in `call'
```

I tried running assets:clobber and rerunning generate, no change at all.

### Mastodon instance

toot.dusepo.co.uk

### Mastodon version

v4.3.0

### Technical details

Node version: 22.9.0
Ruby version: 3.3.5
Using corepack.

**Comment by Foritus** [comment]
Ok I have no idea why the rails wrapper command doesn't work, but running the node build directly fixed it:

```
npm run build:production
```

in the "live" root folder. Good luck to people who got here via search!

**Comment by renchap** [comment]
The asset compilation failed (`Compilation failed:` in your log above). I suspect this is due to Webpack consuming too much memory. If it worked with `build:production` then you should be fine, your server maybe had more memory available at this time, or it was near the limit and running it outside of the ruby process helped.

**Comment by Foritus** [comment]
That seems plausible :smile: Probably a good argument for me to do this stuff offline in Docker and not try to compile things on the actual instance VM. Feel free to close this, I figure at worst it's a bit of SEO for people having the same issue.

**Comment by pageuppagedown** [comment]
> The asset compilation failed (`Compilation failed:` in your log above). I suspect this is due to Webpack consuming too much memory. If it worked with `build:production` then you should be fine, your server maybe had more memory available at this time, or it was near the limit and running it outside of the ruby process helped.

Running out of RAM was my problem. Thanks for the help!

**Comment by lits101** [comment]
'build:production' worked for me too after the pre-compile step of the instructions failed.

**Comment by brindledcat** [comment]
Thank-you! `npm run build:production` fixed my issue.

**Comment by jstewart612** [comment]
This does not work from my Docker install.

**Comment by siliciferous** [comment]
Adding more memory wasn't a quick and easy option for me, so editing config/webpack/production.js and adding `parallelism: 1,` after the `module.exports = merge(sharedConfig, {` line resolved the compilation fail in my case.

**Comment by jsalort** [comment]
> This does not work from my Docker install from any mastodon or mastodon-streaming docker image. The former lacks NPM the latter lacks cross-env apparently.
> 
> ```
> root@mastodon-streaming-847b9f46f-h8c9g:/opt/mastodon# npm run build:production
> 
> > build:production
> > cross-env RAILS_ENV=production NODE_ENV=production ./bin/webpack
> 
> sh: 1: cross-env: not found
> root@mastodon-streaming-847b9f46f-h8c9g:/opt/mastodon#
> ```

I have exactly the same behavior as you describe. And additionnally, the web container does not work either. I get:
```
web_1        | [d9d055fb-1ec8-4ad0-ba65-9553e2fcb7fd] ActionView::Template::Error (Webpacker can't find inert.css in /opt/mastodon/public/packs/manifest.json. Possible causes:
web_1        | 1. You want to set webpacker.yml value of compile to true for your environment
web_1        |    unless you are using the `webpack -w` or the webpack-dev-server.
web_1        | 2. webpack has not yet re-run to reflect updates.
web_1        | 3. You have misconfigured Webpacker's config/webpacker.yml file.
web_1        | 4. Your webpack configuration is not creating a manifest.
```

**Comment by TonyHoyle** [comment]
I got the inert.css issue also.  It's already listed as #31568

The fix there works:

`RAILS_ENV=production bundle exec rails assets:clobber
`RAILS_ENV=production bundle exec rails assets:precompile`

**Comment by sousmangoosta** [comment]
For docker installation, if you have a shared volume for sharing the live/public, delete it and let your web container recreate it.

**Comment by rasos** [comment]
`assets-precompile` fail confirmed when upgrading to 4.3.1. Fix suggestions are not applicable on our k8s deployment, where this runs in a separate pod (without resource limits and enough RAM).  Log says:

> mastodon-assets-precompile There was an error while trying to write to `/opt/mastodon/Gemfile.lock`. It is likely that you need to grant write permissions for that path.

In the `mastodon-web` pod we see in `/opt/mastodon/ `

> -rw-r--r--  1 root     root      28284 Oct 21 09:01 Gemfile.lock

**Comment by sousmangoosta** [comment]
> `assets-precompile` fail confirmed when upgrading to 4.3.1. Fix suggestions are not applicable on our k8s deployment, where this runs in a separate pod (without resource limits and enough RAM).

You don't need the precompile step with the official docker image, it's already done.

**Comment by vmstan** [comment]
@Foritus  Is this still an issue for you?

**Comment by Foritus** [comment]
> [@Foritus](https://github.com/Foritus) Is this still an issue for you?

No, my workaround was sufficient and have since given the VM more RAM.
