### ISSUE TITLE
New user creation fails when using SAML

### ISSUE THREAD

**Issue by quartje** [mastodon/mastodon#32653]
### Steps to reproduce the problem

1.Configure SAML, use a specific attribute to as as UID
2. Log in using SAML
3. Existing user succeeeds, non existing user fails
...

### Expected behaviour

User should be created

### Actual behaviour

A 500 error is thrown

### Detailed description

This setup works in 4.2 but breaks in 4.3

SAML is configured with these environment variables
```
SAML_ENABLED=true
SAML_DISPLAY_NAME=SomeName
SAML_UID_ATTRIBUTE=urn:mace:dir:attribute-def:eduPersonNickname
SAML_ATTRIBUTES_STATEMENTS_EMAIL=urn:mace:dir:attribute-def:mail
SAML_ATTRIBUTES_STATEMENTS_FULL_NAME=urn:mace:dir:attribute-def:displayName
SAML_ACS_URL=https://someurl
SAML_ISSUER=https://someissuer
SAML_IDP_SSO_TARGET_URL=https://someurl
SAML_IDP_CERT=somecert
SAML_SECURITY_ASSUME_EMAIL_IS_VERIFIED=true
SAML_ATTRIBUTES_STATEMENTS_VERIFIED=true
```
The error that is thrown is: 

```
NoMethodError (undefined method `will_save_change_to_attribution_domains?' for an instance of Account):
 
app/models/concerns/account/attribution_domains.rb:7:in `block (2 levels) in <module:AttributionDomains>'
app/models/user.rb:206:in `block in mark_email_as_confirmed!'
app/models/user.rb:431:in `wrap_email_confirmation'
app/models/user.rb:204:in `mark_email_as_confirmed!'
app/models/concerns/user/omniauthable.rb:81:in `create_for_auth'
app/models/concerns/user/omniauthable.rb:33:in `find_for_omniauth'
app/controllers/auth/omniauth_callbacks_controller.rb:10:in `block in provides_callback_for'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
lib/public_file_server_middleware.rb:18:in `call'
```

### Mastodon instance

test.social.edu.nl

### Mastodon version

v4.3.1

### Browser name and version

Firefox 131.0.3

### Operating system

Arch Linux

**Comment by quartje** [comment]
Never mind a restart of the container was enough to fix the issue
