### ISSUE TITLE
Asset precompile fails when upgrading to 4.1.4

### ISSUE THREAD

**Issue by vmbrasseur** [mastodon/mastodon#25859]
### Steps to reproduce the problem

Upgrading from 4.1.0 to 4.1.4

1. git fetch && git checkout v4.1.4 into ~mastodon/live
2. run upgrade steps from [4.1.1](https://github.com/mastodon/mastodon/releases/tag/v4.1.1), [4.1.2](https://github.com/mastodon/mastodon/releases/tag/v4.1.2), [4.1.3](https://github.com/mastodon/mastodon/releases/tag/v4.1.3), [4.1.4](https://github.com/mastodon/mastodon/releases/tag/v4.1.4)
3. At the step to precompile the assets (required for 4.1.1), experience errors either with or without NODE_OPTIONS=--openssl-legacy-provider

### Expected behaviour

Assets should precompile successfully

### Actual behaviour

"error:0308010C:digital envelope routines::unsupported" without NODE_OPTIONS, many asset compile failures with it

### Detailed description

Running `RAILS_ENV=production bundle exec rails assets:precompile` results in this error:

```
Compiling...
Compilation failed:
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mastodon/live/node_modules/webpack/lib/util/createHash.js:135:53)
    at ConcatenatedModule._createIdentifier (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:563:16)
    at new ConcatenatedModule (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:445:27)
    at /home/mastodon/live/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:250:26
    at SyncBailHook.eval [as call] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1351:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1342:27)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:675:18
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1185:12
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
```

The first time I saw this error, it was preceded by this message:

```
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
```

Running `npx update-browserslist-db@latest` had no effect on the precompilation error. I searched issues to find more guidance.

This is a Digital Ocean droplet, which node 18. It turns out that Mastodon [doesn't support node 18 yet](https://github.com/mastodon/mastodon/issues/20968), so the workaround is to include `NODE_OPTIONS=--openssl-legacy-provider` in the precompile command. 

However, running `NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production bundle exec rails assets:precompile` results in a different series of errors. The error dump is more than 350 lines long, so I've put the complete text in [this gist](https://gist.github.com/vmbrasseur/079a513d0e04a63ef85b158b3a25058b). The assets appear to be failing with the same error. Here's a representative:

```
ERROR in ./app/javascript/mastodon/containers/mastodon.js 1:1399
Module parse failed: Unexpected token (1:1399)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> import _jsx from"@babel/runtime/helpers/esm/jsx";import PropTypes from'prop-types';import React from'react';import{Helmet}from'react-helmet';import{IntlProvider,addLocaleData}from'react-intl';import{Provider as ReduxProvider}from'react-redux';import{BrowserRouter,Route}from'react-router-dom';import{ScrollContext}from'react-router-scroll-4';import configureStore from'mastodon/store/configureStore';import UI from'mastodon/features/ui';import{fetchCustomEmojis}from'mastodon/actions/custom_emojis';import{hydrateStore}from'mastodon/actions/store';import{connectUserStream}from'mastodon/actions/streaming';import ErrorBoundary from'mastodon/components/error_boundary';import initialState,{title as siteTitle}from'mastodon/initial_state';import{getLocale}from'mastodon/locales';const{localeData,messages}=getLocale();addLocaleData(localeData);const title=process.env.NODE_ENV==='production'?siteTitle:`${siteTitle} (Dev)`;export const store=configureStore();const hydrateAction=hydrateStore(initialState);store.dispatch(hydrateAction);if(initialState.meta.me){store.dispatch(fetchCustomEmojis());}const createIdentityContext=state=>({signedIn:!!state.meta.me,accountId:state.meta.me,disabledAccountId:state.meta.disabled_account_id,accessToken:state.meta.access_token,permissions:state.role?state.role.permissions:0});export default class Mastodon extends React.PureComponent{static childContextTypes={identity:PropTypes.shape({signedIn:PropTypes.bool.isRequired,accountId:PropTypes.string,disabledAccountId:PropTypes.string,accessToken:PropTypes.string}).isRequired};identity=createIdentityContext(initialState);getChildContext(){return{identity:this.identity};}componentDidMount(){if(this.identity.signedIn){this.disconnect=store.dispatch(connectUserStream());}}componentWillUnmount(){if(this.disconnect){this.disconnect();this.disconnect=null;}}shouldUpdateScroll(prevRouterProps,_ref){let{location}=_ref;return!(location.state?.mastodonModalKey&&location.state?.mastodonModalKey!==prevRouterProps?.location?.state?.mastodonModalKey);}render(){const{locale}=this.props;return/*#__PURE__*/_jsx(IntlProvider,{locale:locale,messages:messages},void 0,/*#__PURE__*/_jsx(ReduxProvider,{store:store},void 0,/*#__PURE__*/_jsx(ErrorBoundary,{},void 0,/*#__PURE__*/_jsx(BrowserRouter,{},void 0,/*#__PURE__*/_jsx(ScrollContext,{shouldUpdateScroll:this.shouldUpdateScroll},void 0,/*#__PURE__*/_jsx(Route,{path:"/",component:UI}))),/*#__PURE__*/_jsx(Helmet,{defaultTitle:title,titleTemplate:`%s - ${title}`}))));}}
 @ ./app/javascript/mastodon/main.js 1:127-185 3:225-233 3:252-257 3:673-678
 @ ./app/javascript/packs/application.js
```

There's some possible evidence (#25741) that there's yet another workaround, but it's not clear how to do that.

### Specifications

Mastodon 4.1.4
Ubuntu 22.10 (GNU/Linux 5.19.0-46-generic x86_64)
4 GB memory
Node v18.7.0
.ruby-version 3.0.3

**Comment by FireFury0** [comment]
I am seeing exactly the same problem updating Mastodon on both CentOS Stream 8 and CentOS Stream 9.

**Comment by renchap** [comment]
As you said, Mastodon 4.1 does not support Node 18 and up.

You need to use Node 16 (use `nvm` to install it if needed), Yarn 1 (not Yarn 3 "Berry"). Once those are installed, remove your `node_modules/` folder, rollback any local changes, run `yarn install` then retry pre-compiling.

**Comment by ClearlyClaire** [comment]
`NODE_OPTIONS=--openssl-legacy-provider` should be enough to fix the `ERR_OSSL_EVP_UNSUPPORTED` issue, but the second issue you're facing suggests you have modified your `yarn.lock`. Please ensure you're using stock `package.json` and `yarn.lock`

**Comment by vmbrasseur** [comment]
Thanks, @ClearlyClaire. That was the tip I needed.

Dunno when, but at some point I must've done something to `.ruby-version`, `Gemfile.lock`, and `yarn.lock`, since those showed as modified when I did the checkout of v4.1.4. Unfortunately, I didn't notice that at the time of checkout.

Fixing those files so they're the ones from the repo resolved the problem. `NODE_OPTIONS=--openssl-legacy-provider` now works for the asset precompile again. Update to v4.1.4 and then to v4.1.5 successful.

Thanks again for the help. <3
