### ISSUE TITLE
Undefined method `image_description`

### ISSUE THREAD

**Issue by paulober** [mastodon/mastodon#27161]
### Steps to reproduce the problem

1. Connect to Mastodon with Ivory
2. Open Web logs

### Expected behaviour

All works

### Actual behaviour

Error server having issues

### Detailed description

```
INFO -- : [90aadba9-0403-46ac-ade8-46daf61bc09e] method=GET path=/api/v1/timelines/public format=*/* controller=Api::V1::Timelines::PublicController action=show status=500 allocations=176955 duration=637.79 view=0.00 db=28.50
F, [2023-09-26T20:34:19.552998 #15] FATAL -- : [90aadba9-0403-46ac-ade8-46daf61bc09e]   
[90aadba9-0403-46ac-ade8-46daf61bc09e] NoMethodError (undefined method `image_description' for #<PreviewCard id: 14877, url: "https://www.youtube.com/watch?v=OBnMl8Jk_Rg", title: "GNOME Shell 45 Extensions Port Guide", description: "", image_file_name: "9b0af1d92ae5dd8e.jpg", image_content_type: "image/jpeg", image_file_size: 28528, image_updated_at: "2023-09-26 16:15:47.261553000 +0000", type: "video", html: "<iframe width=\"200\" height=\"113\" src=\"https://www....", author_name: "Just Perfection", author_url: "https://www.youtube.com/@jperfection", provider_name: "YouTube", provider_url: "https://www.youtube.com/", width: 200, height: 113, created_at: "2023-09-26 16:15:47.451472000 +0000", updated_at: "2023-09-26 16:15:47.451472000 +0000", embed_url: "", image_storage_schema_version: 1, blurhash: "UE8z=Qxu8_t7j?j[ogof4Ts:?cR*kDayV@WB", language: nil, max_score: nil, max_score_at: nil, trendable: nil, link_type: nil>):
```

### Mastodon version

v4.2.0

### Technical details

Since I updated my docker nodes to v4.2.0 neither third party apps nor the website works anymore. In streaming I get constantly "Error: Invalid access token", in web I get the error I posted in the detailed description and in sidekiq I get following errors:
```
2023-09-26T20:36:45.450Z pid=6 tid=s7nu class=ActivityPub::ProcessingWorker jid=0689fee0f19b5e333fe81d6b elapsed=0.049 INFO: fail
2023-09-26T20:36:45.450Z pid=6 tid=s7nu WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"ingress","backtrace":true,"args":[109965879583220973,"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"Hashtag\":\"as:Hashtag\",\"movedTo\":{\"@id\":\"as:movedTo\",\"@type\":\"@id\"},\"alsoKnownAs\":{\"@id\":\"as:alsoKnownAs\",\"@type\":\"@id\"},\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"featured\":{\"@id\":\"toot:featured\",\"@type\":\"@id\"},\"featuredTags\":{\"@id\":\"toot:featuredTags\",\"@type\":\"@id\"},\"schema\":\"http://schema.org#\",\"PropertyValue\":\"schema:PropertyValue\",\"value\":\"schema:value\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"blurhash\":\"toot:blurhash\",\"discoverable\":\"toot:discoverable\",\"indexable\":\"toot:indexable\",\"memorial\":\"toot:memorial\",\"votersCount\":\"toot:votersCount\",\"Device\":\"toot:Device\",\"Ed25519Signature\":\"toot:Ed25519Signature\",\"Ed25519Key\":\"toot:Ed25519Key\",\"Curve25519Key\":\"toot:Curve25519Key\",\"EncryptedMessage\":\"toot:EncryptedMessage\",\"publicKeyBase64\":\"toot:publicKeyBase64\",\"deviceId\":\"toot:deviceId\",\"claim\":{\"@type\":\"@id\",\"@id\":\"toot:claim\"},\"fingerprintKey\":{\"@type\":\"@id\",\"@id\":\"toot:fingerprintKey\"},\"identityKey\":{\"@type\":\"@id\",\"@id\":\"toot:identityKey\"},\"devices\":{\"@type\":\"@id\",\"@id\":\"toot:devices\"},\"messageFranking\":\"toot:messageFranking\",\"messageType\":\"toot:messageType\",\"cipherText\":\"toot:cipherText\",\"suspended\":\"toot:suspended\"}],\"id\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841/activity\",\"type\":\"Create\",\"actor\":\"https://mastodon.social/users/SleightWryder\",\"published\":\"2023-09-26T19:14:06Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://mastodon.social/users/SleightWryder/followers\",\"https://tapbots.social/users/paul\"],\"object\":{\"id\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841\",\"type\":\"Note\",\"inReplyTo\":\"https://tapbots.social/users/paul/statuses/111128720639834424\",\"published\":\"2023-09-26T19:14:06Z\",\"url\":\"https://mastodon.social/@SleightWryder/111133042041108841\",\"attributedTo\":\"https://mastodon.social/users/SleightWryder\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://mastodon.social/users/SleightWryder/followers\",\"https://tapbots.social/users/paul\"],\"sensitive\":false,\"atomUri\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841\",\"inReplyToAtomUri\":\"https://tapbots.social/users/paul/statuses/111128720639834424\",\"conversation\":\"tag:tapbots.social,2023-09-26:objectId=8793847:objectType=Conversation\",\"content\":\"<p><span class=\\\"h-card\\\" translate=\\\"no\\\"><a href=\\\"https://tapbots.social/@paul\\\" class=\\\"u-url mention\\\">@<span>paul</span></a></span> It was created from slave labour. That&#39;s what was wrong. It&#39;s the equivalent of a rape baby.</p>\",\"contentMap\":{\"en\":\"<p><span class=\\\"h-card\\\" translate=\\\"no\\\"><a href=\\\"https://tapbots.social/@paul\\\" class=\\\"u-url mention\\\">@<span>paul</span></a></span> It was created from slave labour. That&#39;s what was wrong. It&#39;s the equivalent of a rape baby.</p>\"},\"attachment\":[],\"tag\":[{\"type\":\"Mention\",\"href\":\"https://tapbots.social/users/paul\",\"name\":\"@paul@tapbots.social\"}],\"replies\":{\"id\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"next\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841/replies?only_other_accounts=true&page=true\",\"partOf\":\"https://mastodon.social/users/SleightWryder/statuses/111133042041108841/replies\",\"items\":[]}}},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://mastodon.social/users/SleightWryder#main-key\",\"created\":\"2023-09-26T19:14:09Z\",\"signatureValue\":\"U/fM7Emd8U52u5Cg+EsI6WC6QzM0yZVnar7dXb+9issmQOZASvnCJvnme3TwVbPJlznpPYrQ3ruTe3JPLjSyyj+kOUj5kjbTyrWB13MVcE2cG6P0SU1m7sfGhHwh2yyUOZmvpo2+N116VWWCp6zAMSCreUEJy+UL6ptMx0PqBoIRWpf66hTgthe7rH02qZJINr/53kjz2gr9M62oFDXCJJEvjuFGnisLVvTUeE2nUwu/TY7/2+8NIPgmvzbjwA/jHXSdYrQC4lO8ajPXze7JET7NK0r+CMVjpiQivjbG/+2H+MycjEVR17yAKTG44zRwXss43oTtpnh1Wp61q/kraw==\"}}",null,"Account"],"class":"ActivityPub::ProcessingWorker","jid":"0689fee0f19b5e333fe81d6b","created_at":1695755654.557208,"enqueued_at":1695760605.4008126,"error_message":"Neither PUB key nor PRIV key: unsupported","error_class":"OpenSSL::PKey::RSAError","failed_at":1695755654.7776887,"retry_count":7,"error_backtrace":"eJyLVtLPLyjRLypNqtTPyUyCMIz1jPQMgOKpecXFOfoF2amVekVJVsamZlaZ\neQoJmXmZJZmJOZlVqepKOqRrz0stJ19fLABmBDpo\n","retried_at":1695758154.9505622}}
2023-09-26T20:36:45.450Z pid=6 tid=s7nu WARN: OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: unsupported
2023-09-26T20:36:45.450Z pid=6 tid=s7nu WARN: /opt/ruby/lib/ruby/3.2.0/openssl/pkey.rb:356:in `initialize'
/opt/ruby/lib/ruby/3.2.0/openssl/pkey.rb:356:in `new'
/opt/ruby/lib/ruby/3.2.0/openssl/pkey.rb:356:in `new'
2023-09-26T20:37:32.676Z pid=6 tid=s6ya class=FeedInsertWorker jid=cb3f75e32d82db8376587610 INFO: start
2023-09-26T20:37:32.695Z pid=6 tid=s6ya class=FeedInsertWorker jid=cb3f75e32d82db8376587610 elapsed=0.019 INFO: fail
2023-09-26T20:37:32.695Z pid=6 tid=s6ya WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"FeedInsertWorker","args":[111130711795461895,109956100774665790,"home",{"update":null}],"jid":"cb3f75e32d82db8376587610","created_at":1695720089.7166674,"enqueued_at":1695760652.67638,"error_message":"PG::UndefinedColumn: ERROR:  column lists.exclusive does not exist\nLINE 1: ... FROM \"lists\" WHERE \"lists\".\"account_id\" = $1 AND \"lists\".\"e...\n                                                             ^\n","error_class":"ActiveRecord::StatementInvalid","failed_at":1695720089.7388954,"retry_count":11,"retried_at":1695745899.7575839}}
2023-09-26T20:37:32.695Z pid=6 tid=s6ya WARN: ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column lists.exclusive does not exist
LINE 1: ... FROM "lists" WHERE "lists"."account_id" = $1 AND "lists"."e...
                                                             ^
2023-09-26T20:37:32.695Z pid=6 tid=s6ya WARN: /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
2023-09-26T20:37:37.195Z pid=6 tid=s88m class=FeedInsertWorker jid=a3df91312f6ab56cb2d4e7ea INFO: start
2023-09-26T20:37:37.217Z pid=6 tid=s88m class=FeedInsertWorker jid=a3df91312f6ab56cb2d4e7ea elapsed=0.021 INFO: fail
2023-09-26T20:37:37.217Z pid=6 tid=s88m WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"FeedInsertWorker","args":[111133356695871782,109956100774665790,"home",{"update":null}],"jid":"a3df91312f6ab56cb2d4e7ea","created_at":1695760447.696969,"enqueued_at":1695760657.1951094,"error_message":"PG::UndefinedColumn: ERROR:  column lists.exclusive does not exist\nLINE 1: ... FROM \"lists\" WHERE \"lists\".\"account_id\" = $1 AND \"lists\".\"e...\n                                                             ^\n","error_class":"ActiveRecord::StatementInvalid","failed_at":1695760447.7230704,"retry_count":3,"retried_at":1695760540.274489}}
2023-09-26T20:37:37.217Z pid=6 tid=s88m WARN: ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column lists.exclusive does not exist
LINE 1: ... FROM "lists" WHERE "lists"."account_id" = $1 AND "lists"."e...
                                                             ^
2023-09-26T20:37:37.217Z pid=6 tid=s88m WARN: /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
```

So at the moment all users at my instance can't use mastodon anymore since the update to v4.2.0

**Comment by ClearlyClaire** [comment]
It seems like you may not have run database migrations, or not restarted the nodes after performing them.

**Comment by paulober** [comment]
I recreated all containers and I thought it'll do the db migration when starting-up after checking the db scheme version.

**Comment by ClearlyClaire** [comment]
It does not! Running the migrations is your responsibility, as it allows near-zero-downtime migrations. Please read the update steps in https://github.com/mastodon/mastodon/releases/tag/v4.2.0

**Comment by paulober** [comment]
Done, that fixed the issue. Though some account no have no profile image even after removing media attachments (and previews) with the admin cli and clearing the cache.
