### ISSUE TITLE
4.2.3: ActionView::Template::Error (Webpacker can't find media/images/preview.png

### ISSUE THREAD

**Issue by DavidCWGA** [mastodon/mastodon#28244]
### Steps to reproduce the problem

1. Upgrade to 4.2.3

### Expected behaviour

Working upgrade

### Actual behaviour

Error in the log, pages are blank

### Detailed description

After upgrading to 4.2.3, pages load blank.

The following error appears in the logs:

```
Dec 05 15:30:53 bundle[3215]: F, [2023-12-05T15:30:53.442535 #3215] FATAL -- : [9027bd7e-f7ad-44ff-96f2-9172baf93339]
Dec 05 15:30:53 bundle[3215]: [9027bd7e-f7ad-44ff-96f2-9172baf93339] ActionView::Template::Error (Webpacker can't find media/images/preview.png in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Dec 05 15:30:53 bundle[3215]: 1. You want to set webpacker.yml value of compile to true for your environment
Dec 05 15:30:53 bundle[3215]:    unless you are using the `webpack -w` or the webpack-dev-server.
Dec 05 15:30:53 bundle[3215]: 2. webpack has not yet re-run to reflect updates.
Dec 05 15:30:53 bundle[3215]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Dec 05 15:30:53 bundle[3215]: 4. Your webpack configuration is not creating a manifest.
Dec 05 15:30:53 bundle[3215]: Your manifest contains:
Dec 05 15:30:53 bundle[3215]: {
Dec 05 15:30:53 bundle[3215]: }
Dec 05 15:30:53 bundle[3215]: ):

```

"bundle exec rails assets:precompile" results in the following error:

```
Compilation failed:
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/babel-plugin-lodash/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)

```

### Mastodon instance

private

### Mastodon version

v4.2.3

### Browser name and version

Safari 17.1.2

### Operating system

macOS 14.1.2

### Technical details

Server is Debian 11.8 on x86_64, no docker.

**Comment by DavidCWGA** [comment]
I deleted and re-checked-out yarn.lock and re-ran precompile and now I get a _lot_ of errors. Screenfuls of it.

[precompile-error.txt](https://github.com/mastodon/mastodon/files/13574238/precompile-error.txt)

**Comment by DavidCWGA** [comment]
git status says:

```
HEAD detached at v4.2.3
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   yarn.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dist/<our domain>.conf

no changes added to commit (use "git add" and/or "git commit -a")
```

yarn install after deleting node_modules appears to succeed:

```
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^1.0.2 || 2 || 3 || 4"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
[4/6] Linking dependencies...
warning " > emoji-mart@3.0.1-j" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".
warning " > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning " > react-notification@6.8.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-swipeable-views@0.14.0" has incorrect peer dependency "react@^15.3.0 || ^16.0.0 || ^17.0.0".
warning "react-swipeable-views > react-swipeable-views-utils > react-event-listener@0.6.6" has incorrect peer dependency "react@^16.3.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
$ husky install
husky - Git hooks installed
Done in 19.83s.
```

Precompile still fails, with the same errors as in the attached text file above.

**Comment by mjankowski** [comment]
Most of that output is expected logs/warnings/etc of the build process -- that said, the section in the middle about `@rails/ujs` are actual errors.

My guess is that you have updated that JS package to rails/ujs 7.1, but the code in 4.2.3 that uses that lib still expects 7.0 (there are unreleased changes in `main` that perform the upgrade and change the usage).

**Comment by DavidCWGA** [comment]
OK, I've solved my own problem.

I was doing simply "yarn install" instead of "yarn install --frozen-lockfile". I had no idea the difference would be so catastrophic, but, there we are.
