### ISSUE TITLE
Roles not being displayed as badge on user profiles

### ISSUE THREAD

**Issue by downeymj** [mastodon/mastodon#20723]
### Steps to reproduce the problem

1. For a given role, ensure "Display role as badge on user profiles" site setting is enabled
2. Add user "X" to that role. 
3. View profile of user "X".

### Expected behaviour

Badge for given role is displayed on user profile

### Actual behaviour

No badge is displayed on user profile

### Detailed description

Seems none of the badges are being displayed now on profiles (e.g. Admin), especially those for newly-created roles.

### Specifications

Mastodon 4.0.1

**Comment by AndresJ551** [comment]
Maybe a long shot, but this can be related:
```
12: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
lib/mastodon/rack_middleware.rb:9:in `call'
app/controllers/concerns/localized.rb:11:in `set_locale'
app/views/home/index.html.haml:7
app/views/shared/_web_app.html.haml:1
app/views/shared/_web_app.html.haml:9
app/helpers/application_helper.rb:223:in `render_initial_state'
app/models/account.rb:124:in `user_role'
app/models/user.rb:157:in `role'
app/presenters/initial_state_presenter.rb:9:in `role'
10:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
9:   = render_initial_state
7:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
8: 
11: 
6: 
Did you mean?  role):
ActionView::Template::Error (undefined local variable or method `role_id' for #<User id: 1, email: ...>
Did you mean?  role' duration=59.23 view=0.00 db=7.68

method=GET path=/ format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: undefined local variable or method `role_id' for #<User id: 1, email: ...>
```
I get that error after updating from 3.5 to 4.0.1 using docker-compose.

**Comment by AndresJ551** [comment]
Nevermind, I forgot to restart the instance after doing the rake db:migrate.

**Comment by ineffyble** [comment]
Duplicate of #19922.
