### ISSUE TITLE
Search returns error 500 (ElasticSearch 6)

### ISSUE THREAD

**Issue by mkody** [mastodon/mastodon#17070]
### Steps to reproduce the problem

1. Try to search for anything, either `#MastoArt`, `@kdy` or even just `Kody`
2. See there's an error 500 message

### Expected behaviour

I get results from /api/v2/search

### Actual behaviour

Error 500 is returned by the server

### Specifications

#16915 might be related to this regression?

Issue happening at `im-in.space`, currently running glitch-soc but synched at 1c826471e7d964f0fdb2dc2b89dcd5a19c017538

Ubuntu 20.04.3 LTS
Node v14.17.5
ruby 3.0.3p157
ElasticSearch 6.8.18

Request was `GET /api/v2/search?q=%23MastoArt&resolve=true&limit=10`
In `mastodon-web` service's log I get:
```
method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=500 error='NoMethodError: undefined method `fetch' for 24:Integer' duration=13.31 view=0.00 db=2.24

NoMethodError (undefined method `fetch' for 24:Integer):

app/services/tag_search_service.rb:79:in `from_elasticsearch'
app/services/tag_search_service.rb:10:in `call'
app/services/search_service.rb:62:in `perform_hashtags_search!'
app/services/search_service.rb:20:in `block in call'
app/services/search_service.rb:12:in `call'
app/controllers/api/v2/search_controller.rb:19:in `search_results'
app/controllers/api/v2/search_controller.rb:12:in `index'
```

---

Previous issue at glitch-soc while troubleshooting: https://github.com/glitch-soc/mastodon/issues/1639

**Comment by Gargron** [comment]
You need to upgrade Elasticsearch to 7.x. I ran into the same problem. Thankfully it’s as simple as apt install from the right source.

**Comment by mkody** [comment]
That would be the solution, fine for me.

Just asking while thinking of administrators in general: is entirely (suddenly?) dropping 6.x support a good thing? AFAIK, 6.8 is still supported until 8.x is out.
And with Mastodon's documentation [still giving instructions for adding the 6.x branch](https://docs.joinmastodon.org/admin/optional/elasticsearch/), I'd maybe expect some kind of support for a version or two while giving instructions that 6.x is now deprecated for Mastodon.

**Comment by Gargron** [comment]
I am definitely not happy that Elasticsearch 6.x and 7.x break compatibility in such a way. I mean, compare it to PostgreSQL, where if your application was working on 9.4, you can upgrade to 12 without having to update your application code... Frankly, I don't know who to blame here exactly, Elasticsearch or the authors of the Chewy gem. But a new version of Mastodon isn't out yet and so it makes sense that instructions are not updated. We don't give instructions for main, we give instructions for the last stable version (currently 3.4.x)

**Comment by ClearlyClaire** [comment]
Maybe we could downgrade Chewy to 7.0.x for the time being? But it would involve reverting some of the changes from #16915

**Comment by Gargron** [comment]
If you ask me, most dependency updates are entirely, utterly useless; a cascade of busywork forced by someone, somewhere down the dependency chain deciding to add some random flag for some random feature that one person needs. When was the last time we ever *used* anything added in a dependency update, or benefited from a fix, in the sea of endless dependabot-generated PRs? Hell, even most security fixes are from development tools that never see the light of production. And yet, we must always stay updated, in fear that one day it would become too hard to upgrade to a version with a critical security fix, in the hopes, that somehow new code will run faster somehow. Package management, what a concept.

There's no specific reason to upgrade Chewy. There's no reason to downgrade it either. It's all just churn. If we downgrade it, we'll just have to upgrade it later anyway. There is no escape.

**Comment by ClearlyClaire** [comment]
I think one reason was to have Elasticsearch 7 support, which 7.0.x provides without dropping compatibility with Elasticsearch 6

**Comment by nightpool** [comment]
Just so I understand correctly, Chewy dropped support for Elasticsearch 6 in a minor version release? isn't that a semver violation?

**Comment by ClearlyClaire** [comment]
they explicitly state they aren't following semver

**Comment by mkody** [comment]
> We don't give instructions for main, we give instructions for the last stable version (currently 3.4.x) 

Ah sorry, I wasn't saying I'd expect docs to be up-to-date with main, but more that it could be updated in advance if Mastodon already has a workaround to work with 7.x (even if it's not ideal).

---

I totally get the frustration with dependencies and their dependencies.
It's even more of a mess when they don't follow SemVer like in this case just so they can track certain versions of an upstream dep (like a NodeJS version, webpack, or in this case ElasticSearch).
So using an "old version" shouldn't be a problem as long as it tracks the required ElasticSearch version and is still supported.

But what's done is done and as I see there's no great point in downgrading now.
Like it was done with Mastodon 3.4.0 for NodeJS and Postgres, write in the next release note that the required ElasticSearch version is now 7.x for full text search.
The upgrade path is thankfully straightforward too.

I'll be closing this issue since it was resolved.
Everyone, have a nice week!

**Comment by ClearlyClaire** [comment]
> But what's done is done and as I see there's no great point in downgrading now.

I mean, it would avoid an extra step for people updating to the next Mastodon release.

**Comment by mkody** [comment]
At some point it should be necessary to upgrade anyway. What's holding us to make it happen now than later?

Like Eugen said, it will happen at some point, especially with 6.8.x marked as possible EOL since 2020-11-20 and will be when 8.x is out (for which I have no idea when Elastic, the company, decides to do so). And without support, it might not work for whatever reason they choose with a new release of a distro or have incompatibilities with a Java version.

**Comment by ClearlyClaire** [comment]
Yeah it's not a huge deal, I just think it's nicer if we give people longer to update their system dependencies, and especially avoid having a version of Mastodon supporting only a different version of Elasticsearch than the previous one. But it seems like 3.4.x actually supports Elasticsearch 7 already, so it's fine by me. Just needs a heads-up in the release notes.

**Comment by osresearch** [comment]
The install instructions need an update -- they still add the 6.x repo: https://docs.joinmastodon.org/admin/optional/elasticsearch/#install

Having a better error message would also help track down what is happening; I upgrade our mastodon instance and the only indication is that some things start returning 500 errors. It required quite some digging to figure out what was breaking and to find this discussion.

**Comment by ClearlyClaire** [comment]
The change in requirements is clearly documented in the release notes for 3.5.0rc1.

Regarding updating the docs, there's a PR open for this that @Gargron just has to merge: https://github.com/mastodon/documentation/pull/926

You're right that the error message is obscure, I will see how it could be improved.
