### ISSUE TITLE
Cannot use j/k to move between posts in the bookmarks column of the advanced web UI

### ISSUE THREAD

**Issue by rluetzner** [mastodon/mastodon#25512]
### Steps to reproduce the problem

1. Use 'n' on the keyboard to select the column with the pinned bookmarks in the advanced web UI.
2. Try j/k to move between posts.

### Expected behaviour

j/k should allow me to move down/up between posts.

### Actual behaviour

Nothing happens. It works as expected in other columns though.

### Detailed description

When using the multi-column advanced web UI, the j/k hotkeys to move between posts don't work in the bookmarks column.

The hotkeys work fine elsewhere and I'm able to use '1', '2', '3', etc. to move to other columns.

I'm not a frontend developer, but another issue gave me the idea to check with web developer tools for any log messages.

```text
Uncaught TypeError: this.props.statusIds.indexOf is not a function
    getCurrentStatusIndex status_list.js:40
    handleMoveDown status_list.js:49
    handleHotkeyMoveDown status.js:273
    callback SwipeableViews.js:702
    u scrollLeft.js:9
    _handleKey utils.js:6
    handleKey computeIndex.js:4
    d scrollTop.js:4
status_list.js:40:8

Uncaught TypeError: this.props.statusIds.indexOf is not a function
    getCurrentStatusIndex status_list.js:40
    handleMoveUp status_list.js:43
    handleHotkeyMoveUp status.js:269
    callback SwipeableViews.js:702
    u scrollLeft.js:9
    _handleKey utils.js:6
    handleKey computeIndex.js:4
    d scrollTop.js:4
status_list.js:40:8
```

### Specifications

**Mastodon v4.1.2**

It's a frontend issue, which I've encountered on **Windows** and **Linux**.

I've observed this issue in two different browsers: **LibreWolf** (a **Firefox** derivative) and **Brave** (a **Chrome** derivative).

**Comment by rluetzner** [comment]
I've edited the issue description. Initially I thought it was a problem with the third column of the advanced web UI, but it is in fact an issue when one of the columns are pinned bookmarks.

**Comment by ClearlyClaire** [comment]
I can reproduce the issue. It also occurs in the favourites list and the explore tab.

This is a regression from #22121, that started using Immutable.js' `OrderedSet` in place of Immutable.js' `List` which behave in similar ways for most of our uses but does not implement `indexOf` which the keyboard notification code relies on.

**Comment by rluetzner** [comment]
Thank you for looking into it so quickly. 🙂

**Comment by rluetzner** [comment]
Okay, I understand what #22121 is trying to solve. Would [toIndexedSeq()](https://immutable-js.com/docs/v3.8.2/OrderedSet/#toIndexedSeq()) help? Sadly I don't have a ready to test Mastodon instance available and no matter what I try I can't modify the remote JavaScript to try out the code.

I expect that there are some performance drawbacks to this solution, but I can't tell how severe they might be.

**Comment by ClearlyClaire** [comment]
I *think* so, but this should most probably use memoization (see `createSelector` from `reselect`). Do you want to try fixing it, or should I go ahead?

**Comment by rluetzner** [comment]
If it's alright, I'd leave it up to you, because I have no way to test the change.

**Comment by rluetzner** [comment]
Thank you @ClearlyClaire . 🙂 

I just read through the Vagrant Dev setup and will try it out later. To get ready, so I can fix things myself the next time.
