### PR TITLE
Fix #1491 - Fix broken notifications, broken Link header parsing for …

### LINKED ISSUE #1491: Notifications fail to load
Bad commit https://github.com/tootsuite/mastodon/commit/12f72e1740cd91929419c82c6b782393e306994c

```
application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:39
TypeError: status.getIn is not a function
    at Object.render (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:30)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper._renderValidatedComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at Object.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at ReactCompositeComponentWrapper.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
    at Object.mountComponent (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:1110)
    at ReactCompositeComponentWrapper.performInitialMount (application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:702)
(anonymous) @ application-40ef2e74c5e2f7d364d4364f187e18e4b1cd3a785debb8a00a1532ba1e37b483.js:39
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### PR DESCRIPTION
**Pull request by Gargron**
…exclude_types

### CODE REVIEW

**Comment by carlosjs23** [comment]
This introduce :

```
TypeError: _httpLinkHeader2.default.parseParams is not a function
Stack trace:
[123]</_httpLinkHeader2.default.parseAttrs@https://mastodones.club/assets/application-6404d5c4351f7c87199e9c531e5199f7675975349057aafee3f2ed8d70ef7dc2.js:38:2286
[259]</Link.prototype.parse@https://mastodones.club/assets/application-6404d5c4351f7c87199e9c531e5199f7675975349057aafee3f2ed8d70ef7dc2.js:352:2541
[259]</Link.parse@https://mastodones.club/assets/application-6404d5c4351f7c87199e9c531e5199f7675975349057aafee3f2ed8d70ef7dc2.js:352:1914
[17]</exports.getLinks@https://mastodones.club/assets/application-6404d5c4351f7c87199e9c531e5199f7675975349057aafee3f2ed8d70ef7dc2.js:30:1426
refreshNotifications/</<@https://mastodones.club/assets/application-6404d5c4351f7c87199e9c531e5199f7675975349057aafee3f2ed8d70ef7dc2.js:29:13526
```

**Comment by Fastidious** [comment]
@carlosjs23 are you saying that you merged the `fix-notifications` branch into your latest install, and got that error?

**Comment by carlosjs23** [comment]
@Fastidious  I apply this PR as a patch, in master. Could it be the cause ?.

**Comment by Fastidious** [comment]
@carlosjs23 If you have the master running, it means your notifications aren’t working, correct? If they aren’t, this one is meant to fix that, yes. But if you have applied other unapproved patches, just like you are trying to apply this one, there is no way of telling…

**Comment by carlosjs23** [comment]
@Fastidious you right, when applying this patch I get the error I mention before, I have not applied other patches not approved, only this one.

**Comment by Wonderfall** [comment]
I merged the branch into my fork, for me it's working.

**Comment by Gargron** [comment]
@carlosjs23 The fix contains an update to yarn.lock. Run `yarn` to install an upgraded dependency.

**Comment by Fastidious** [comment]
I can’t wait for this to make it to `master`! Have been running blind (no notification) for a few hours now. 😄

**Comment by carlosjs23** [comment]
@Gargron maybe we need to put the update commands together in one step. To avoid these situations :+1:

**Comment by Fastidious** [comment]
Is this addressing remote follows too? It seems I can’t do that anymore either, getting "Could not find the required redirect URL for your account.” I have not patched yet, waiting until approved.

**Comment by zaksoup** [comment]
I've deployed this branch and I see a few "oops" errors in the UI, and the JS console shows 

```
TypeError: _httpLinkHeader2.default.parseParams is not a function
    at Function._httpLinkHeader2.default.parseAttrs (application-222b4a3….js:24002)
    at Link.parse (application-222b4a3….js:34043)
    at Function.Link.parse (application-222b4a3….js:33987)
    at getLinks (application-222b4a3….js:14285)
    at application-222b4a3….js:14163
```

Digging in deeper.

**Comment by Fastidious** [comment]
@zaksoup See https://github.com/tootsuite/mastodon/pull/1548#issuecomment-293330623.

**Comment by zaksoup** [comment]
@Fastidious yup, just read it an deleted. Sorry for noise. Attempting redeploy now. Some funniness since I'm deploying to Cloud Foundry (a PaaS like Heroku) and the build pack doesn't love asset precompilation so I precompile locally. Lots of moving parts I'm trying to lock down.

**Comment by mjankowski** [comment]
Running this branch locally after an `npm install` resolves the notifications column errors for me.

**Comment by ericblade** [comment]
Fixes my broken Searches

**Review by krainboltgreene — APPROVED** [review]
