### ISSUE TITLE
 Can't login after upgrade to v3.4.3

### ISSUE THREAD

**Issue by kuratowsky** [mastodon/mastodon#16951]
### Expected behaviour

Enter the credentials and should to show the user panel

### Actual behaviour

auth/sign_in shows a 500 error

### Steps to reproduce the problem

1. Put the user and Pass
2. Press sign in button

### Specifications

The mastodon instance is mine. Today I upgraded it to the latest release.

I'm using Ubuntu 20.04.3 LTS
Firefox 94
Chromium 95

In my mobile phone, I've got installed the PWA and works fine, because the user is already logged in.

**Comment by Gargron** [comment]
Please provide the error log

**Comment by kuratowsky** [comment]
Here it is,
I hope it helps!

```
[9ad818c0-b174-4803-a4a2-4277df5a296c] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 error='NoMethodError: undefined method `remember_me' for #<Auth::SessionsController:0x0000000010b080>' duration=315.13 view=0.00 db=36.28
[9ad818c0-b174-4803-a4a2-4277df5a296c]   
[9ad818c0-b174-4803-a4a2-4277df5a296c] NoMethodError (undefined method `remember_me' for #<Auth::SessionsController:0x0000000010b080>):
[9ad818c0-b174-4803-a4a2-4277df5a296c]   
[9ad818c0-b174-4803-a4a2-4277df5a296c] app/controllers/auth/sessions_controller.rb:27:in `block in create'
[9ad818c0-b174-4803-a4a2-4277df5a296c] app/controllers/auth/sessions_controller.rb:25:in `create'
[9ad818c0-b174-4803-a4a2-4277df5a296c] app/controllers/concerns/localized.rb:16:in `block in set_locale'
[9ad818c0-b174-4803-a4a2-4277df5a296c] app/controllers/concerns/localized.rb:15:in `set_locale'
```

Cheers

**Comment by ClearlyClaire** [comment]
It seems like you are still running 3.4.2 code instead of 3.4.3.

**Comment by kuratowsky** [comment]
Oh, sorry. It's true. My bad.
Thanks and sorry guys.

**Comment by vkill** [comment]
+1
