### ISSUE TITLE
After updating to v4.7.0: mastodon-streaming does not start anymore

### ISSUE THREAD

**Issue by alxhu-dev** [mastodon/mastodon#40225]
### Steps to reproduce the problem

1. Update Mastodon from v4.6.6 to v4.7.0
2. Try to access /api/v1/streaming/health

### Expected behaviour

Return OK

### Actual behaviour

A message "We're sorry, but something went wrong on our end. "

### Detailed description

Mastodon-streaming service fails to start:

```
Aug 20 18:23:49 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Scheduled restart job, restart counter is at 3.
Aug 20 18:23:49 m-greifswaldlgbt systemd[1]: Started mastodon-streaming@4000.service - mastodon-streaming on port 4000.
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: /home/mastodon/live/node_modules/undici/lib/web/cache/cachestorage.js:20
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     webidl.util.markAsUncloneable(this)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:                 ^
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: TypeError: webidl.util.markAsUncloneable is not a function
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at new CacheStorage (/home/mastodon/live/node_modules/undici/lib/web/cache/cachestorage.js:20:17)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Object.<anonymous> (/home/mastodon/live/node_modules/undici/index.js:179:25)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._compile (node:internal/modules/cjs/loader:1521:14)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module.load (node:internal/modules/cjs/loader:1266:32)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._load (node:internal/modules/cjs/loader:1091:12)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module.require (node:internal/modules/cjs/loader:1289:19)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at require (node:internal/modules/helpers:182:18)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/lib/api.js:12:33)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._compile (node:internal/modules/cjs/loader:1521:14)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: Node.js v20.20.2
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Scheduled restart job, restart counter is at 4.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Start request repeated too quickly.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.

```

### Mastodon instance

greifswald.lgbt

### Mastodon version

v4.7.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 4.0.6 (2026-07-14 revision 03b6d3f889) +PRISM [aarch64-linux]`
- Node.js version: `v20.20.2`

**Comment by alxhu-dev** [comment]
Seems to be an error with my setup.

I'm using a machine with LXC containers. I have Nginx, Postgres, Elasticsearch and Mastodon in diffrent containers. (The main reason behind that is to be able to have multiple Mastodon instances on the same server which share the same Nginx, Postgres and Elasticsearch instance).

The Nginx container is not able to connect to the Mastodon container anymore. It throws "111: Connection refused".

**Comment by alxhu-dev** [comment]
If anyone with a simlear setup sees this:

Mastodon seems to only listen on 0.0.0.0. Nginx sometimes tries to connect via IPv4, sometimes via IPv6, since it's trying to access it via it's .lxd-domain. IPv6 requests are getting refused.

**Comment by alxhu-dev** [comment]
I recieve this error:

```
Aug 20 18:23:49 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Scheduled restart job, restart counter is at 3.
Aug 20 18:23:49 m-greifswaldlgbt systemd[1]: Started mastodon-streaming@4000.service - mastodon-streaming on port 4000.
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: /home/mastodon/live/node_modules/undici/lib/web/cache/cachestorage.js:20
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     webidl.util.markAsUncloneable(this)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:                 ^
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: TypeError: webidl.util.markAsUncloneable is not a function
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at new CacheStorage (/home/mastodon/live/node_modules/undici/lib/web/cache/cachestorage.js:20:17)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Object.<anonymous> (/home/mastodon/live/node_modules/undici/index.js:179:25)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._compile (node:internal/modules/cjs/loader:1521:14)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module.load (node:internal/modules/cjs/loader:1266:32)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._load (node:internal/modules/cjs/loader:1091:12)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module.require (node:internal/modules/cjs/loader:1289:19)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at require (node:internal/modules/helpers:182:18)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/lib/api.js:12:33)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]:     at Module._compile (node:internal/modules/cjs/loader:1521:14)
Aug 20 18:23:50 m-greifswaldlgbt node[1371]: Node.js v20.20.2
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Scheduled restart job, restart counter is at 4.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Start request repeated too quickly.
Aug 20 18:23:50 m-greifswaldlgbt systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.

```

**Comment by alxhu-dev** [comment]
The node version seems to be too low. I've updated it (`node --version` displays `v24.19.0` now), but it still seems to use v20.20.2?

**Comment by alxhu-dev** [comment]
Nevermind, I had to install nvm because I could not figure out how to update the Node version Mastodon uses

**Comment by sneakers-the-rat** [comment]
thanks for this, would have taken me awhile to identify this without the issue here.

for upgrading system node, i just did [these commands](https://docs.joinmastodon.org/admin/install/#node-js) and upgraded with apt:

```shell
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
apt update
apt install nodejs --only-upgrade
systemctl restart mastodon-streaming
```
