### ISSUE TITLE
Libre Translate not working in 4.2.0 beta 2

### ISSUE THREAD

**Issue by gerdemann** [mastodon/mastodon#26620]
### Steps to reproduce the problem

1. Add Libre Translate environment variables
2. Go to the Web UI
3. 500 error on /api/v1/instance/translation_languages 

### Expected behaviour

No 500 error

### Actual behaviour

500 error

### Detailed description

You can find it in the logs:
```
INFO -- : [f01af4d2-294b-4574-8528-a45b83e07601] method=GET path=/api/v1/instance/translation_languages format=html controller=Api::V1::Instances::TranslationLanguagesController action=show status=500 allocations=28476 duration=108.94 view=0.00 db=21.26
FATAL -- : [f01af4d2-294b-4574-8528-a45b83e07601]
[f01af4d2-294b-4574-8528-a45b83e07601] NoMethodError (undefined method `without' for nil:NilClass):
[f01af4d2-294b-4574-8528-a45b83e07601]
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:21:in `block (2 levels) in languages'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:20:in `to_h'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:20:in `block in languages'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:40:in `block in request'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/request.rb:133:in `perform'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:33:in `request'
[f01af4d2-294b-4574-8528-a45b83e07601] app/lib/translation_service/libre_translate.rb:19:in `languages'
[f01af4d2-294b-4574-8528-a45b83e07601] app/controllers/api/v1/instances/translation_languages_controller.rb:19:in `block in set_languages'
[f01af4d2-294b-4574-8528-a45b83e07601] app/controllers/api/v1/instances/translation_languages_controller.rb:19:in `set_languages'
[f01af4d2-294b-4574-8528-a45b83e07601] app/controllers/concerns/localized.rb:11:in `set_locale'
[f01af4d2-294b-4574-8528-a45b83e07601] lib/mastodon/rack_middleware.rb:9:in `call'
[f01af4d2-294b-4574-8528-a45b83e07601] lib/public_file_server_middleware.rb:18:in `call'
```

### Mastodon instance

wohnzimmer.social

### Mastodon version

v4.2.0+beta2

### Technical details

Docker setup with officially recommended docker-compose.

**Comment by b2cc** [comment]
Interesting - this might be specific to the publicly available docker image?. We also run 4.2.0-beta2, but we built the image from source via the `Dockerfile` and we don't see this problem - Libretranslate still works as expected.

PS: we use a self-hosted Libretranslate instance without API key authentication so the only ENV we use is `LIBRE_TRANSLATE_ENDPOINT`. Not sure if this is in play here, just thought I'd mention it.

**Comment by gerdemann** [comment]
This is the response of /languages:
```

[{"code":"en","name":"English"},{"code":"ar","name":"Arabic"},{"code":"az","name":"Azerbaijani"},{"code":"ca","name":"Catalan"},{"code":"zh","name":"Chinese"},{"code":"cs","name":"Czech"},{"code":"da","name":"Danish"},{"code":"nl","name":"Dutch"},{"code":"eo","name":"Esperanto"},{"code":"fi","name":"Finnish"},{"code":"fr","name":"French"},{"code":"de","name":"German"},{"code":"el","name":"Greek"},{"code":"he","name":"Hebrew"},{"code":"hi","name":"Hindi"},{"code":"hu","name":"Hungarian"},{"code":"id","name":"Indonesian"},{"code":"ga","name":"Irish"},{"code":"it","name":"Italian"},{"code":"ja","name":"Japanese"},{"code":"ko","name":"Korean"},{"code":"fa","name":"Persian"},{"code":"pl","name":"Polish"},{"code":"pt","name":"Portuguese"},{"code":"ru","name":"Russian"},{"code":"sk","name":"Slovak"},{"code":"es","name":"Spanish"},{"code":"sv","name":"Swedish"},{"code":"tr","name":"Turkish"},{"code":"uk","name":"Ukranian"}]
```

**Comment by c960657** [comment]
Compared to the API docs, the `targets` key is missing.
https://libretranslate.com/docs/#/translate/get_languages

Which version of LibreTranslate are you running?

**Comment by gerdemann** [comment]
I was using version 1.3.2, but after updating Libretranslate it now works.
Was there a change in 4.2.0? Maybe you can mention this in the upgrade instructions.

**Comment by ClearlyClaire** [comment]
There were changes in 4.2.0, but we were not aware of versioning restrictions for the Libretranslate API we were using. Going to look into it.

**Comment by ClearlyClaire** [comment]
Seems like this was added in LibreTranslate 1.3.3.

**Comment by gabriel-samfira** [comment]
I know this is closed, but in case someone stumbles across this, I also had to pass in the `--url-prefix=/translate` option to the `libretranslate` systemd service. Mastodon seems to use that prefix.
