### ISSUE TITLE
NoMethodError: undefined method `indexable='…

### ISSUE THREAD

**Issue by cluelessdev404** [mastodon/mastodon#26691]
### Steps to reproduce the problem

1. View processed jobs in Sidekiq
2. See that many account jobs are failing

### Expected behaviour

Fail rate should be very low

### Actual behaviour

Fail rate is at about 50%

### Detailed description

Since I updated to 4.2.0b2 a few days ago, checking the Sidekiq panel showed that about 40-50% of all processes were failing. 

The affected jobs are `Activitypub::ProcessingWorker` and `ThreadResolveWorker`. 

The errors given are the following:

`NoMethodError: undefined method indexable=' for #<Account id: 1234567890, username: “example", domain: "example.com", private_key: nil, public_key…`

and

`OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: no start line`

### Mastodon instance

orchard.social

### Mastodon version

v4.2.0beta2

### Technical details

Server is set up via Docker and official beta images

**Comment by renchap** [comment]
You probably forgot to run the migrations. Then you need to restart your web & sidekiq processes.

**Comment by cluelessdev404** [comment]
> You probably forgot to run the migrations. Then you need to restart your web & sidekiq processes.

Ah I thought that was only from 4.1.6 to 4.2.0, thanks so much for the help. I’ll keep this issue open for a little bit longer as I monitor it for more unexpected errors.

**Comment by ClearlyClaire** [comment]
Closing as this most likely was due to forgetting to run migrations. Please let us know if you still have issues.
