### ISSUE TITLE
/streaming/user and /streaming/user/notification are not working on version 4.2.11

### ISSUE THREAD

**Issue by ssOleg** [mastodon/mastodon#31467]
### Steps to reproduce the problem

1. Initiate a Streaming Request:

- Make a GET streaming request to either the /streaming/user/notification or /streaming/user endpoint.

2. Wait for Incoming Data:

-  Keep the connection open and wait for new messages or data to be received through the streaming connection.

3. Observe Received Data:

- Notice that while heartbeat messages appear as expected, mention notifications are not being received.

### Expected behaviour

notifications should appear in stream as expected

### Actual behaviour

no notifications in stream

### Detailed description

I was using "/streaming/user/notification" to manage replays in my elixir based application. However, after last update it stopped to work. Not sure if some params need to changed or if API was changed somehow. I still see heartbeat but no other messages appear.

### Mastodon instance

mastodon.kaiman.uk

### Mastodon version

v4.2.11

### Technical details

I use docker compose with "ghcr.io/mastodon/mastodon:v4.2.11"

Note: not sure if it is related/helpful but I saw this error in logs 

```
sidekiq-1    | 2024-08-16T19:05:52.706Z pid=7 tid=2khf WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"LocalNotificationWorker","args":[112933604811709660,17338,"Mention","mention"],"jid":"08bd729d56691160284a8051","created_at":1723834936.1009328,"enqueued_at":1723835152.5992892,"error_message":"undefined method `user_role' for nil:NilClass","error_class":"NoMethodError","failed_at":1723834936.327193,"retry_count":3,"retried_at":1723835034.2850657}}
sidekiq-1    | 2024-08-16T19:05:52.706Z pid=7 tid=2khf WARN: NoMethodError: undefined method `user_role' for nil:NilClass
sidekiq-1    | 2024-08-16T19:05:52.707Z pid=7 tid=2khf WARN: /opt/mastodon/app/services/notify_service.rb:90:in `from_staff?'
sidekiq-1    | /opt/mastodon/app/services/notify_service.rb:116:in `blocked?'
sidekiq-1    | /opt/mastodon/app/services/notify_service.rb:19:in `call'
(indexing_scheduler)

```

**Comment by hugogameiro** [comment]
I am also seeing this on my end.

**Comment by lrmikestone** [comment]
As @hugogameiro mentioned, we're seeing this behavior on Fosstodon.

**Comment by drkp** [comment]
I'm seeing this behavior on discuss.systems (running v4.2.11), and can confirm that it's caused by #31271 / 49c5577a36002b5fc664b5937332b8f339c1d089.

Specifically, it looks like mention notifications are not being sent to local users when the sender has a higher role than the mentioned user.

**Comment by ThisIsMissEm** [comment]
@renchap I can possibly spend time on this in a week (need to finish FIRES stuff first), though, would this be changing with the new notification policies and notification grouping?

**Comment by brookmiles** [comment]
In addition to notifications not being sent, Private Mentions which are not replies will also not show up in the receiver's Private Mentions

**Comment by nikclayton** [comment]
Re https://github.com/mastodon/mastodon/issues/31483#issuecomment-2295259289 -- are the folks that are seeing this with the streaming API only seeing it affect mention notifications, or does it affect other types of notification as well (e.g., follow, favourite)?

**Comment by nativehyun** [comment]
The same symptom is appearing in pointless.chat after upgrading to 4.2.11.

**Comment by eighth-layer** [comment]
We're experiencing the same symptoms on gamerstavern.online on v4.2.11. No notifications or DMs from users with a higher roles.

**Comment by unbelauscht** [comment]
The issue was tagged `status/identified`, so please subscribe to the issue instead of bumping it, since you will only spam people subscribed to the issue thank you

**Comment by renchap** [comment]
Thanks for all your reports, and sorry for this!

It has been fixed in #31484, and we just released Mastodon 4.2.12 with the fix.
