### ISSUE TITLE
Error 500ing after upgrading from 3.4.4 to main caused by editing (I think)

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#17376]
### Steps to reproduce the problem

1. git checkout main
2. recompile
3. launch

### Expected behaviour

Normal mastodon

### Actual behaviour

UI shows with no posts, error 500 in the UI and this in the logs:
```
Jan 25 18:04:57 t1c bundle[573684]: [18dac882-ad6c-40d1-b3bf-4510536edc53] NoMethodError (undefined method `edited_at' for #<Status id: 107686301836564002, uri: "https://trollian.space/users/Paradox/statuses/1076...", text: "<p><span class=\"bbcode__color\" data-bbcodecolor=\"#...", created_at: "2022-01-26 02:02:42.000000000 +0000", updated_at: "2022-01-26 02:02:44.644810000 +0000", in_reply_to_id: nil, reblog_of_id: nil, url: "https://trollian.space/@Paradox/107686301709069895", sensitive: false, visibility: "public", spoiler_text: "", reply: false, language: "en", conversation_id: 571016, local: false, account_id: 106697928563147575, application_id: nil, in_reply_to_account_id: nil, poll_id: nil, deleted_at: nil, local_only: nil, content_type: nil>
Jan 25 18:04:57 t1c bundle[573684]: Did you mean?  edited?):
Jan 25 18:04:57 t1c bundle[573684]: [18dac882-ad6c-40d1-b3bf-4510536edc53]
Jan 25 18:04:57 t1c bundle[573684]: [18dac882-ad6c-40d1-b3bf-4510536edc53] app/controllers/api/v1/timelines/home_controller.rb:11:in `show'
Jan 25 18:04:58 t1c bundle[573683]: [ea4da130-84c9-4760-9205-d8aac88b79d2] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=72.90 view=59.39 db=9.42
```

### Specifications

main

**Comment by ClearlyClaire** [comment]
Did you run migrations before reloading `mastodon-web`?

**Comment by ThatOneCalculator** [comment]
I did, yes. The issue is that i completely effing corrupted my database
