### ISSUE TITLE
Submitting a status twice with the same Idempotency-Key returns 500 instead of the existing status

### ISSUE THREAD

**Issue by martinmuc** [mastodon/mastodon#40399]
### Steps to reproduce the problem

Submit the same status twice with an identical `Idempotency-Key`. The second request fails with HTTP 500.

Reproducible in `rails console` on an affected instance (`direct` visibility, so nothing is published):

```ruby
account = Account.find_by(username: 'someone', domain: nil)
key = SecureRandom.hex(8)
PostStatusService.new.call(account, text: 'test', visibility: 'direct', idempotency: key)  # ok
PostStatusService.new.call(account, text: 'test', visibility: 'direct', idempotency: key)  # raises
```

Over the API this happens whenever a client repeats a request carrying the same `Idempotency-Key`: when the first response was lost in transit, or when a user re-submits a draft that the web UI kept after an apparently failed request.

### Expected behaviour

The second request is recognised as a duplicate and returns the status created by the first request, with HTTP 200. That is what `Idempotency-Key` is for.

### Actual behaviour

The duplicate is detected correctly, but the request fails with HTTP 500:

```
NoMethodError (undefined method 'account' for nil):
app/services/process_hashtags_service.rb:6:in 'ProcessHashtagsService#call'
app/services/post_status_service.rb:163:in 'PostStatusService#postprocess_status!'
app/services/post_status_service.rb:61:in 'PostStatusService#call'
app/controllers/api/v1/statuses_controller.rb:31:in 'Api::V1::StatusesController#create'
```

Nothing is lost and nothing is posted twice: the status from the first request exists and has been distributed normally. But the client is told the request failed, so users try again, which reproduces the error.

### Detailed description

The early return for a detected duplicate sits inside the block passed to `with_redis_lock`:

```ruby
def with_idempotency
  return yield unless idempotency_given?

  with_redis_lock("idempotency:lock:status:#{@account.id}:#{@options[:idempotency]}") do
    return idempotency_duplicate if idempotency_duplicate?

    yield

    redis.setex(idempotency_key, 3_600, @status.id)
  end
end
```

A `return` inside a block returns from the method the block is written in, so it leaves `with_idempotency`, not `call`. Execution continues in `call`:

```ruby
with_idempotency do
  ...
end

unless scheduled?
  postprocess_status!   # @status is nil here
  bump_potential_friendship!
end
```

`@status` is only assigned in `process_status!`, which never runs for a duplicate, so `postprocess_status!` operates on `nil`. The return value of `with_idempotency` is discarded.

This was introduced in #37879. Before that change the early return was in `call` itself and correctly skipped post-processing:

```ruby
return idempotency_duplicate if idempotency_given? && idempotency_duplicate?
```

The same code is present in v4.6.0 through v4.7.1 and in `main`.

### Mastodon instance

troet.cafe

### Mastodon version

v4.7.0
