### PR TITLE
Set InstancePresenter to `Auth::RegistrationsController#create` (regression from #5308)

### LINKED ISSUE #5365: Error 500 occurs when registering new account
*On master @ b8bae96*:

Attempting to register for an account fails with an error 500 and the following output from ``mastodon-web``:

```
[cb61977b-efa8-4752-91d8-5881533ef645] method=POST path=/auth format=html controller=Auth::RegistrationsController action=create status=500 error='ActionView::Template::Error: undefined method `thumbnail' for nil:NilClass' duration=180.74 view=0.00 db=20.79
[cb61977b-efa8-4752-91d8-5881533ef645]
[cb61977b-efa8-4752-91d8-5881533ef645] ActionView::Template::Error (undefined method `thumbnail' for nil:NilClass):
[cb61977b-efa8-4752-91d8-5881533ef645]     1: - thumbnail = @instance_presenter.thumbnail
[cb61977b-efa8-4752-91d8-5881533ef645]     2: = opengraph 'og:site_name', t('about.hosted_on', domain: site_hostname)
[cb61977b-efa8-4752-91d8-5881533ef645]     3: = opengraph 'og:url', url_for(only_path: false)
[cb61977b-efa8-4752-91d8-5881533ef645]     4: = opengraph 'og:type', 'website'
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

### PR DESCRIPTION
**Pull request by ykzts**
Resolve #5365

### CODE REVIEW

**Comment by ykzts** [comment]
cc @takayamaki

**Review by Gargron — APPROVED** [review]

**Comment by takayamaki** [comment]
🙇
