### ISSUE TITLE
"ActionView::Template::Error" after updating to 4.2.0 (Docker)

### ISSUE THREAD

**Issue by Sieboldianus** [mastodon/mastodon#27063]
### Steps to reproduce the problem

1. I updated my instance form 4.1.9 to 4.2.0.
2. When browsing the instance, "We're sorry, but something went wrong on our end." is displayed
3. In the backend, I see "ActionView::Template::Error" (see Detailed description for error output)

For the meantime, I reverted to `4.1.9` and this worked to make the issue go away.

### Expected behaviour

No issues, since no Docker update instructions are given

### Actual behaviour

"ActionView::Template::Error" shows, instance browsing not possible

### Detailed description

```
docker-web-1        | I, [2023-09-22T13:44:53.691644 #20]  INFO -- : [d80bcc3c-20de-43bb-b949-0e6e8e73b1e9] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 allocations=96 duration=0.42 view=0.27 db=0.00
docker-web-1        | I, [2023-09-22T13:44:58.520911 #20]  INFO -- : [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] method=GET path=/ format=html controller=HomeController action=index status=500 allocations=3587 duration=10.94 view=0.00 db=1.73
docker-web-1        | F, [2023-09-22T13:44:58.521838 #20] FATAL -- : [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]      7:
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]      8:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]      9:
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]     10:   = render_initial_state
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]     11:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]     12:
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]     13: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a]
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/models/concerns/has_user_settings.rb:103:in `setting_default_privacy'
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/helpers/application_helper.rb:191:in `render_initial_state'
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/views/shared/_web_app.html.haml:10
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/views/shared/_web_app.html.haml:1
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/views/home/index.html.haml:7
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] app/controllers/concerns/localized.rb:11:in `set_locale'
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] lib/mastodon/rack_middleware.rb:9:in `call'
docker-web-1        | [3007de6e-cfdf-4001-9036-15f7e4a0dd0a] lib/public_file_server_middleware.rb:18:in `call'
docker-sidekiq-1    | 2023-09-22T13:44:58.718Z pid=6 tid=2ije uniquejobs=reaper INFO: Nothing to delete; exiting.
docker-sidekiq-1    | 2023-09-22T13:44:58.721Z pid=6 tid=2ije uniquejobs=reaper INFO: Nothing to delete; exiting.
docker-sidekiq-1    | 2023-09-22T13:44:58.888Z pid=6 tid=2ila INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuses_scheduler)
docker-sidekiq-1    | 2023-09-22T13:44:58.888Z pid=6 tid=2ilm INFO: queueing Scheduler::Trends::RefreshScheduler (trends_refresh_scheduler)
docker-sidekiq-1    | 2023-09-22T13:44:58.890Z pid=6 tid=2ime class=Scheduler::Trends::RefreshScheduler jid=c7ed6d14c38c933140984c12 INFO: start
docker-sidekiq-1    | 2023-09-22T13:44:58.892Z pid=6 tid=2k8i class=Scheduler::ScheduledStatusesScheduler jid=42678af17734574245808d18 INFO: start
docker-sidekiq-1    | 2023-09-22T13:44:58.900Z pid=6 tid=2k8i class=Scheduler::ScheduledStatusesScheduler jid=42678af17734574245808d18 elapsed=0.007 INFO: done
docker-sidekiq-1    | 2023-09-22T13:44:58.925Z pid=6 tid=2ime class=Scheduler::Trends::RefreshScheduler jid=c7ed6d14c38c933140984c12 elapsed=0.035 INFO: done
docker-sidekiq-1    | 2023-09-22T13:44:59.189Z pid=6 tid=2k7e INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
docker-sidekiq-1    | 2023-09-22T13:44:59.189Z pid=6 tid=2k86 INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
docker-sidekiq-1    | 2023-09-22T13:44:59.189Z pid=6 tid=2iki INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
docker-sidekiq-1    | 2023-09-22T13:44:59.193Z pid=6 tid=2k72 class=Scheduler::AccountsStatusesCleanupScheduler jid=49caa383631c48f7260d2007 INFO: start
docker-sidekiq-1    | 2023-09-22T13:44:59.194Z pid=6 tid=2inu class=Scheduler::IndexingScheduler jid=cc3875d678a2dbf5bfada1a1 INFO: start
docker-sidekiq-1    | 2023-09-22T13:44:59.196Z pid=6 tid=2ini class=Scheduler::SuspendedUserCleanupScheduler jid=8eb259794f1b8fff47256368 INFO: start
docker-sidekiq-1    | 2023-09-22T13:44:59.198Z pid=6 tid=2inu class=Scheduler::IndexingScheduler jid=cc3875d678a2dbf5bfada1a1 elapsed=0.004 INFO: done
docker-sidekiq-1    | 2023-09-22T13:44:59.201Z pid=6 tid=2ini class=Scheduler::SuspendedUserCleanupScheduler jid=8eb259794f1b8fff47256368 elapsed=0.005 INFO: done
docker-sidekiq-1    | 2023-09-22T13:44:59.204Z pid=6 tid=2k72 class=Scheduler::AccountsStatusesCleanupScheduler jid=49caa383631c48f7260d2007 elapsed=0.011 INFO: done
```

### Technical details

If this is happening on your own Mastodon server, please fill out those:

Latest docker image from `tootsuite/mastodon:4.2.0`.

**Comment by Sieboldianus** [comment]
Can be closed, I had to run:
```bash
docker compose run --rm web rails db:migrate
```

The complete commands:
```bash
# nano .env
# update version to 4.2.0 tag
docker compose pull
docker-compose run --rm web rails db:migrate
docker compose up -d && docker compose logs --follow
```
