### ISSUE TITLE
v4.1.8 DeepL translation: 500 internal server error

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#26983]
### Steps to reproduce the problem

On v4.1.8 click to translate content using DeepL.

### Expected behaviour

Translated content

### Actual behaviour

Error: 500 internal server error

### Mastodon instance

test instance

### Mastodon version

v4.1.8

### Browser name and version

All

### Operating system

All

### Technical details

Log shows:
````
...translate format=html controller=Api::V1::Statuses::TranslationsController action=create status=500 error='NoMethodError: undefined method `model_name' for String:Class

NoMethodError (undefined method `model_name' for String:Class
Did you mean?  module_parent):

app/controllers/api/v1/statuses/translations_controller.rb:14:in `create'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
lib/public_file_server_middleware.rb:18:in `call'

````

**Comment by msviba** [comment]
Same experience

Log:
```
[53804] *      Workers: 2
[53804] *     Restarts: (✔) hot (✖) phased
[53804] * Preloading application
[53804] * Listening on http://10.10.0.11:3000
[53804] Use Ctrl-C to stop
[53804] - Worker 0 (PID: 53870) booted in 0.01s, phase: 0
[53804] - Worker 1 (PID: 53871) booted in 0.0s, phase: 0
[ba802b48-d1a5-4618-8b98-eff9289ab70f]
[ba802b48-d1a5-4618-8b98-eff9289ab70f] NoMethodError (undefined method `model_name' for String:Class

          object.class.model_name.to_s.underscore
                      ^^^^^^^^^^^
Did you mean?  module_parent):
[ba802b48-d1a5-4618-8b98-eff9289ab70f]                             [ba802b48-d1a5-4618-8b98-eff9289ab70f] app/controllers/api/v1/statuses/translations_controller.rb:14:in `create'
[ba802b48-d1a5-4618-8b98-eff9289ab70f] app/controllers/concerns/localized.rb:11:in `set_locale'
[ba802b48-d1a5-4618-8b98-eff9289ab70f] lib/mastodon/rack_middleware.rb:9:in `call'
[5479089c-8725-4240-b940-4b26a768b4d5]                             [5479089c-8725-4240-b940-4b26a768b4d5] NoMethodError (undefined method `model_name' for String:Class                                  
          object.class.model_name.to_s.underscore                                        ^^^^^^^^^^^
Did you mean?  module_parent):
[5479089c-8725-4240-b940-4b26a768b4d5]                             [5479089c-8725-4240-b940-4b26a768b4d5] app/controllers/api/v1/statuses/
```

**Comment by msviba** [comment]
I've rolled back to 417, 416, and finally the v4.1.5 works. So bug is already in v4.1.6

**Comment by spiezmaestro** [comment]
> I've rolled back to 417, 416, and finally the v4.1.5 works. So bug is already in v4.1.6

Can't confirm. For me it was still working fine on 4.1.7.

**Comment by piotr-sikora-v** [comment]
I have same issue after upgrade:

```
[c389af9b-77de-4565-abe8-be240ad4cc3c] method=POST path=/api/v1/statuses/111092366959816123/translate format=html controller=Api::V1::Statuses::TranslationsController action=create status=500 error='NoMethodError: undefined method `model_name' for String:Class
Did you mean?  module_parent' duration=29.57 view=0.00 db=2.58
[c389af9b-77de-4565-abe8-be240ad4cc3c]   
[c389af9b-77de-4565-abe8-be240ad4cc3c] NoMethodError (undefined method `model_name' for String:Class
Did you mean?  module_parent):
[c389af9b-77de-4565-abe8-be240ad4cc3c]   
[c389af9b-77de-4565-abe8-be240ad4cc3c] app/controllers/api/v1/statuses/translations_controller.rb:14:in `create'
[c389af9b-77de-4565-abe8-be240ad4cc3c] app/controllers/concerns/localized.rb:11:in `set_locale'
[c389af9b-77de-4565-abe8-be240ad4cc3c] lib/mastodon/rack_middleware.rb:9:in `call'
[c389af9b-77de-4565-abe8-be240ad4cc3c] lib/public_file_server_middleware.rb:18:in `call'
```

**Comment by joenepraat** [comment]
Can confirm on 4.1.8. 

4.1.7 and before worked normally.

**Comment by joenepraat** [comment]
This has probably to do with https://github.com/mastodon/mastodon/security/advisories/GHSA-2693-xr3m-jhqr. Any idea @ClearlyClaire @Gargron etc?

**Comment by joenepraat** [comment]
**Note: **  This is also an issue when using **LibreTranslate**.

**Comment by msviba** [comment]
I confirm that v4.1.8 has new bug: Not translating EN -> CZ via DeepL. In v4.1.7 it really works.

But in earlier versions is another bug with exactly same error message in log. And it appears during translation CZ -> CZ (translation button should be invisible?)

**Comment by hugogameiro** [comment]
Solved by #26990 thanks!
