### ISSUE TITLE
NoMethodError require_tos_interstitial in logged in user's Web UI

### ISSUE THREAD

**Issue by rahilarious** [mastodon/mastodon#34782]
### Steps to reproduce the problem

After updating containers from 2025-05-07-security nightly to 2025-05-23 nightly & then performing db migration.
Web UI shows up fine when not logged in.
`/admin` UI also works fine when logged in
Server is fine as Android app client is working fine.
No errors in mastodon-streaming or sidekiq or db containers.

Logs:

```
`NoMethodError (undefined method 'require_tos_interstitial?' for an instance of User): app/controllers/concerns/web_app_controller_concern.rb:50:in 'WebAppControllerConcern#redirect_to_tos_interstitial!'
app/controllers/concerns/localized.rb:11:in 'Localized#set_locale'
lib/mastodon/middleware/socket_cleanup.rb:11:in 'Mastodon::Middleware::SocketCleanup#call'
lib/mastodon/middleware/public_file_server.rb:20:in 'Mastodon::Middleware::PublicFileServer#call'`
```

### Expected behaviour

WebUI should work for logged in user

### Actual behaviour

showing "We're sorry, but something went wrong on our end" for logged in user

### Mastodon instance

thoughts.rahil.rocks

### Mastodon version

v4.4.0-nightly.2025-05-23

### Browser name and version

Firefox android 138.0.4

### Operating system

Android 15

**Comment by ClearlyClaire** [comment]
Please make sure you have run database migrations and restarted the Mastodon services after doing so.

**Comment by rahilarious** [comment]
> Please make sure you have run database migrations and restarted the Mastodon services after doing so.

yes. That's given after updating.
I've ran db migrations (mentioned in  *Steps to reproduce* ) I've also removed old ones and made new containers.

**Comment by ClearlyClaire** [comment]
It really looks like the `mastodon-web` process has not been restarted after the database migrations.

**Comment by rahilarious** [comment]
> It really looks like the `mastodon-web` process has not been restarted after the database migrations.

I'm using containers. I've stopped, removed existing container & then started new one. My instance is clearly up (see thoughts.rahil.rocks )& WebUI (non logged) is clearly working.

**Comment by ClearlyClaire** [comment]
Yes, but have you restarted the containers *after* running migrations? The error you're seeing (`undefined method 'require_tos_interstitial?' for an instance of User`) is caused by the application code loading from a database schema that is older than the migration that introduced the `require_tos_interstitial` column to the `users` table.

Since Mastodon loads the database schema at application launch, the order of operations is important: restarting the container, then migrating, without restarting the container/service afterwards means the up-to-date Mastodon code is still running with the information from the pre-migration database schema, and is not aware of `require_tos_interstitial`.

**Comment by rahilarious** [comment]
> Yes, but have you restarted the containers _after_ running migrations? 

apparently I did not. After restarting it is working. Thanks much Claire. Apologies for the trouble.
